on : push
jobs : 
    first_job :
      runs-on : windows-latest
      steps :
        - run : node --version
        - run : npm --version
        - uses : actions/checkout@v3
        - run : npm ci
        - run : node index.js
        - run : npx eslint .